/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductsProductRouteImport } from './routes/products.$product'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProductsCategoryCategoryRouteImport } from './routes/products.category.$category'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductRoute = ProductsProductRouteImport.update({
  id: '/products/$product',
  path: '/products/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryCategoryRoute =
  ProductsCategoryCategoryRouteImport.update({
    id: '/products/category/$category',
    path: '/products/category/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$product': typeof ProductsProductRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$product': typeof ProductsProductRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/products/$product': typeof ProductsProductRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/category/$category': typeof ProductsCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/products/$product'
    | '/blog/'
    | '/products/'
    | '/products/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/products/$product'
    | '/blog'
    | '/products'
    | '/products/category/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/products/$product'
    | '/blog/'
    | '/products/'
    | '/products/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductsProductRoute: typeof ProductsProductRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryCategoryRoute: typeof ProductsCategoryCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$product': {
      id: '/products/$product'
      path: '/products/$product'
      fullPath: '/products/$product'
      preLoaderRoute: typeof ProductsProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/category/$category': {
      id: '/products/category/$category'
      path: '/products/category/$category'
      fullPath: '/products/category/$category'
      preLoaderRoute: typeof ProductsCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductsProductRoute: ProductsProductRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryCategoryRoute: ProductsCategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
